### ISSUE TITLE
proxy error how to slove it?

### ISSUE THREAD

**Issue by DoiiarX** [cordiverse/http#6]
![image](https://github.com/cordiverse/http/assets/25550075/0a58ec1d-8217-447c-bd3e-3690a28f6400)
proxy error how to slove it?

**Comment by shigma** [comment]
Please make sure you configure your `proxyAgent` to something like `socks://127.0.0.1:7890`, instead of using `http://` scheme.

**Comment by DoiiarX** [comment]
> Please make sure you configure your `proxyAgent` to something like `socks://127.0.0.1:7890`, instead of using `http://` scheme.

thanks. successed.
